version: "3.7"

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}

  db:
    image: mysql:5.7
    container_name: "nlw-esports-db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - nlw-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:3306

volumes:
  nlw-mysql-data:
